---
version: 2
formats: []
build:
  os: "ubuntu-22.04"
  tools:
    python: "3.11"
  jobs:
    post_create_environment:
      - pip install uv
    post_install:
      # Instructs uv to use the RTD venv
      - UV_PROJECT_ENVIRONMENT=$READTHEDOCS_VIRTUALENV_PATH uv sync --locked

sphinx:
  configuration: docs/conf.py
