ARG PYTHON

FROM python:${PYTHON}-stretch

RUN apt-get update && apt-get install -y pandoc

ADD docs/requirements.txt /tmp/requirements-docs.txt
RUN pip install -r /tmp/requirements-docs.txt

ADD requirements.txt /tmp/
ADD requirements-dev.txt /tmp/
RUN pip install -r /tmp/requirements-dev.txt

WORKDIR "/nornir"
