import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const repoUrl = 'https://github.com/nornir-automation/nornir';

const sidebars: SidebarsConfig = {
  nornirSidebar: [
    'index',
    {
      type: 'category',
      label: 'Tutorial',
      link: {type: 'doc', id: 'tutorial/index'},
      items: [
        'tutorial/overview',
        'tutorial/python',
        'tutorial/install',
        'tutorial/initializing_nornir',
        'tutorial/inventory',
        'tutorial/tasks',
        'tutorial/task_results',
        'tutorial/failed_tasks',
        'tutorial/processors',
      ],
    },
    {
      type: 'category',
      label: 'How-to guides',
      link: {type: 'generated-index', slug: '/category/how-to-guides'},
      items: [{type: 'autogenerated', dirName: 'howto'}],
    },
    'configuration/index',
    {
      type: 'category',
      label: 'Plugins',
      link: {type: 'doc', id: 'plugins/index'},
      items: ['plugins/execution_model'],
    },
    {
      type: 'category',
      label: 'Upgrading',
      link: {type: 'generated-index', slug: '/category/upgrading'},
      items: [{type: 'autogenerated', dirName: 'upgrading'}],
    },
    'community/plugin_list',
    {
      type: 'category',
      label: 'API reference',
      link: {type: 'generated-index', slug: '/category/api-reference'},
      items: [{type: 'autogenerated', dirName: 'api'}],
    },
    {type: 'link', label: 'Contributing', href: `${repoUrl}/blob/main/CONTRIBUTING.rst`},
    {type: 'link', label: 'Changelog', href: `${repoUrl}/blob/main/CHANGELOG.rst`},
  ],
};

export default sidebars;
