---
name: test nornir
on: [push,pull_request]

jobs:
  linters:
    name: linters
    strategy:
      matrix:
        python-version: [ '3.14' ]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v6
      - name: Install uv
        uses: astral-sh/setup-uv@v8.2.0
        with:
          python-version: ${{ matrix.python-version }}
          enable-cache: true

      - name: Install Dependencies
        run: uv sync --locked

      - name: Run ruff
        run: make ruff
      - name: Run mypy
        run: make mypy
      - name: Run sphinx
        run: |
          sudo apt-get install pandoc
          make docs

  pytest:
    name: Testing on Python ${{ matrix.python-version }} (${{ matrix.platform}})
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        python-version:
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
          - "3.14"
        platform:
          - ubuntu-latest
          - macos-15
          - windows-2022
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v6
      - name: Install uv
        uses: astral-sh/setup-uv@v8.2.0
        with:
          python-version: ${{ matrix.python-version }}
          enable-cache: true

      - name: Install Dependencies
        run: uv sync --locked

      - name: Run pytest
        run: make pytest
        if: ${{ matrix.platform != 'windows-2022' }}

      - name: Run pytest
        run: uv run pytest --cov=nornir --cov-report=term-missing
        if: ${{ matrix.platform == 'windows-2022' }}

      - name: Run nbval
        run: make nbval
        if: ${{ matrix.platform != 'windows-2022' }}

      - name: Report coverage
        uses: coverallsapp/github-action@v2
        if: ${{ matrix.platform == 'ubuntu-latest' && matrix.python-version == '3.11' }}

#  release:
#    name: Releasing to pypi
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v6
#      - name: Install uv
#        uses: astral-sh/setup-uv@v8.2.0
#      - name: Build
#        run: uv build
#      - name: Publish package
#        if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
#        uses: pypa/gh-action-pypi-publish@release/v1
#        with:
#          user: __token__
#          password: ${{ secrets.pypi_password }}
